name: weather
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.9.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  easy_localization: ^3.0.2
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  get_it: ^7.6.0
  injectable: ^2.3.0
  injectable_generator: ^2.4.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
  uses-material-design: true
  
  assets:
    - assets/translations/
