name: weather
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.9.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  easy_localization: ^3.0.2
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.7
  freezed: ^2.4.2
  freezed_annotation: ^2.4.1
  geolocator: ^10.0.0
  get_it: ^7.6.0
  hydrated_bloc: ^9.1.2
  injectable: ^2.3.0
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  path_provider: ^2.1.0
  swipe_refresh: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  lint: ^2.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/image/
    - assets/translations/
    - .env

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf
